### ISSUE TITLE
in laravel6 include not work

### ISSUE THREAD

**Issue by vahidalvandi** [huangdijia/laravel-recaptcha-v3#1]
@include('recaptcha::components.initjs', []) @include('recaptcha::components.field', [])

**Comment by huangdijia** [comment]
Wrong usage, you can see that [https://github.com/huangdijia/laravel-recaptcha-v3#usage](https://github.com/huangdijia/laravel-recaptcha-v3#usage)

**Comment by nam-co** [comment]
Hi, hope you can help me, Im also using @recaptcha_field(), but it just renders @include('recaptcha::components.field', []) in the blade/html, thanks for your time

**Comment by huangdijia** [comment]
> Hi, hope you can help me, Im also using @recaptcha_field(), but it just renders @include('recaptcha::components.field', []) in the blade/html, thanks for your time

upgrade to `v1.2.3`，It's work now
