### ISSUE TITLE
getHost

### ISSUE THREAD

**Issue by amanpatel** [huangdijia/laravel-recaptcha-v3#4]
https://github.com/huangdijia/laravel-recaptcha-v3/blob/0a02d18acf198ae9d57c9cc7ccddffc9fe9422fa/src/Middleware/ReCaptcha.php#L21

Should this be `$request->getHost()` ?

When I'm on `localhost:8000`, even though `localhost` is allowed on my google recaptcha site, I get a "hostname mismatch" error. But if we use getHost() instead of getHttpHost() this problem does not happen.

**Comment by huangdijia** [comment]
v1.3.0 released
